# Generated by Django 4.2.7 on 2023-11-14 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img',
            field=models.ImageField(default='pic', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
